-- table to store clients data
create table if not exists users (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	uuid TEXT NOT NULL UNIQUE,
	name TEXT NOT NULL,
	password TEXT NOT NULL,
	is_proprietary BOOLEAN NOT NULL DEFAULT FALSE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- to storage user emails
create table if not exists emails (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	uuid TEXT NOT NULL UNIQUE,
	id_user INTEGER NOT NULL,
	email TEXT NOT NULL,
	verified BOOLEAN NOT NULL DEFAULT FALSE,
	last_verification_code TIMESTAMP NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

	FOREIGN KEY (id_user) REFERENCES users(id)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

create table if not exists signatures (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	uuid TEXT NOT NULL UNIQUE,
	id_proprietary INTEGER NOT NULL,
	code INTEGER NOT NULL,
	password TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (id_proprietary) REFERENCES users(id)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

create table if not exists signature_history (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	id_signature INTEGER NOT NULL,
	id_user INTEGER NOT NULL,
	validation_result BOOLEAN NOT NULL,
	result_description TEXT NOT NULL,
	checked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

	FOREIGN KEY (id_signature) REFERENCES signatures(id)
	ON DELETE CASCADE
	ON UPDATE CASCADE,

	FOREIGN KEY (id_user) REFERENCES users(id)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

create table if not exists clients (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	id_proprietary INTEGER NOT NULL,
	name TEXT NOT NULL,
	token TEXT NOT NULL UNIQUE,
	root BOOLEAN NOT NULL DEFAULT FALSE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (id_proprietary) REFERENCES users(id)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

create table if not exists client_accesses (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	id_client INTEGER NOT NULL,
	success BOOLEAN NOT NULL DEFAULT FALSE,
	accessed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (id_client) REFERENCES clients(id)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);


